project_name: 'PRJNA1224991'
Genome_Version: "Lsat_Salinas_v11" # Lsat_Salinas_v8,Lsat_Salinas_v11,ITAG4.1,TAIR10.1,GRCm39,hg38
species: 'Lsat Salinas'
client: 内部测试
# short read raw-data
raw_data_path:
  - /data/jzhang/project/Temp/atac_human_PRJNA427322/00.raw_data
# short read samples info
sample_csv: /data/jzhang/project/Temp/atac_human_PRJNA427322/01.workflow/samples.csv
paired_csv: /data/jzhang/project/Temp/atac_human_PRJNA427322/01.workflow/contrasts.csv
# workflow
workflow: /data/jzhang/project/Temp/atac_human_PRJNA427322/01.workflow
# RNAflow Output file
data_deliver: /data/jzhang/project/Temp/atac_human_PRJNA427322/02.data_deliver
# wheather run in HPC Cluster
execution_mode: local #local,cluster
queue_id: default
# Fragment Library Types
Library_Types: fr-firststrand # fr-unstranded,fr-firststrand,fr-secondstrand