# reference:
reference_path : /data/jzhang/reference/ATACFlow_reference
# FastQ Screen Database Root Path (For migration)
# This path should contain subdirectories like 'hg38', 'GRCm39', 'fastq_screen_database', etc.
fastq_screen_db_path: /data/jzhang/reference/fastq_screen_database
# Support gene version
can_use_genome_version:
  - Lsat_Salinas_v11
  - GO
# Bowtie2 Reference PATH
Bowtie2_index:
    Lsat_Salinas_v11:
      index: Lactuca_sativa_V11_ncbi/Lactuca_sativa_V11_ncbi_bowtie2_index/V11_ncbi_bowtie2_index
      gene_gtf: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.only_gene.gtf
      genome_fa: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.fna
      genome_gtf: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.gtf
      genome_gff: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.gff
      bed: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.final.bed12
      go_annotation: Lactuca_sativa_V11_ncbi/GCF_002870075.4-RS_2022_12_gene_ontology.go
      ploidy: 2
    GO:
      obo: go_database/go-basic.obo