# reference:
reference_path : /data/jzhang/reference/ATACFlow_reference
# FastQ Screen Database Root Path (For migration)
# This path should contain subdirectories like 'hg38', 'GRCm39', 'fastq_screen_database', etc.
fastq_screen_db_path: /data/jzhang/reference/fastq_screen_database
# Support gene version
can_use_genome_version:
  - Lsat_Salinas_v11
  - hg38
  - GO
# Bowtie2 Reference PATH
Bowtie2_index:
    Lsat_Salinas_v11:
      index: Lactuca_sativa_V11_ncbi/Lsat_Salinas_v11_index/Lsat_Salinas_v11
      gene_gtf: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.fix_id_gene.gtf
      genome_fa: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.fix_id.fna
      genome_gtf: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.fix_id.gtf
      genome_gff: Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic.fix_id.gff
      bed: Lactuca_sativa_V11_ncbi/Lsat_Salinas_v11.bed12
      go_annotation: Lactuca_sativa_V11_ncbi/GCF_002870075.4-RS_2022_12_gene_ontology.go
      tss_bed:  Lactuca_sativa_V11_ncbi/GCF_002870075.4_Lsat_Salinas_v11_genomic_fix_id_tss.bed
      autosomes: Lactuca_sativa_V11_ncbi/Lactuca_sativa_V11_autosomes.txt
      ploidy: 2
    hg38:
      index: hg38/GRCh38.p14_bowtie2/GRCh38.p14_index
      gene_gtf: hg38/gencode.v49.annotation.gene.gtf
      genome_fa: hg38/GRCh38.p14.genome.fa
      genome_gtf: hg38/gencode.v49.annotation.gtf
      genome_gff: hg38/gencode.v49.annotation.gff3
      bed: hg38/gencode.v49.annotation.bed12
      go_annotation: hg38/goa_human.go
      tss_bed:  hg38/gencode.v49.annotation_tss.bed
      blacklists: hg38/hg38-blacklist.v2.bed
      autosomes: hg38/hg38_autosomes.txt
      ploidy: 2
    GO:
      obo: go_database/go-basic.obo
genome_info:
  Lsat_Salinas_v11:
    effectiveGenomeSize: 2590369317
    chrMID: ChrMT
    plast: Chrpla
  hg38:
    effectiveGenomeSize: 3291585349
    chrMID: chrM
